package com.example.faunaeflora.model;

import com.example.faunaeflora.R;

import java.util.ArrayList;
import java.util.List;

public class ListInitializer {
    public static List<Object> getList() {
        List<Object> list = new ArrayList<>();
        list.add(new Flower(R.drawable.onzehoras, "Onze-Horas", "Maio", "Lá pela hora do almoço para alguns, ou quase para outros, quando o sol começa a entrar a pino, a Portulaca atinge seu florescimento máximo do dia. Por isso, a flor, da família das Portulacaceae, a mesma da pata-de-elefante e da beldroega-graúda, tem como nome popular onze-horas. Fácil de plantar e pouco exigente em cuidados durante o desenvolvimento, a onze-horas possui pétalas delicadas em várias cores vibrantes, tornando-se uma bela flor para ornamentação.\\nA onze-horas gosta muito do sol e tem florescimento o ano inteiro - diminuindo no inverno. Embora o clima quente seja seu preferido, a planta tem boa tolerância a geadas, podendo ser cultivada em todo o país. "));
        list.add(new Animal(R.drawable.tartaruga_aligator, "Tartaruga Aligator", "Conhecida em inglês como Alligator Snapping Turtle e em espanhol como Tortuga caimán, essa espécie é um dos répteis mais agressivos do mundo!\n" +
                "\n" +
                "As tartarugas aligator são comumente encontradas no rio Mississipi e seus afluentes localizados nos Estados Unidos. Claramente, o que diferencia as aligator das demais tartarugas é sua anatomia gigantesca. Esta tartaruga foi considerada a maior espécie já encontrada, com 80 cm de diâmetro e cerca de 100 kg, o que é simplesmente surpreendente! O que faz essa espécie ser um dos répteis mais perigosos é a força de sua mordida que, segundo estimativas, pode alcançar até 178 kgf. Se você não sabe o que este número significa, a mordida de um cachorro é de 68 kgf e o do homem, 70 kgf."));
        list.add(new Flower(R.drawable.violeta, "Violeta", "Junho", "Pequenas, delicadas e de muitas cores. Assim são as violetas, planta cuja beleza tem muitos admiradores. Cercada por folhas verdes cobertas por penugens, que dão a sensação de veludo, as flores são miúdas, abundantes e não apresentam cheiro. Entre os tons mais encontrados estão cor-de-rosa, branco, azul, mesclado e o próprio violeta.\\nMuito popular como ornamento, as violetas são fáceis de cultivar e não ocupam muito espaço. Alcançam tamanho de 15 a 20 centímetros e, com raízes curtas, apresentam bom desenvolvimento em pequenos vasos. Os de plástico são bastante comuns, porém, os modelos de barro são os mais indicados pela capacidade de absorção de umidade. Irrigações em excesso podem levar as raízes ao apodrecimento.\\nA luminosidade é necessária para o seu crescimento, desde que, no entanto, a planta não fique exposta ao sol diretamente. Um outro cuidado que se deve ter é quanto ao ataque de pragas e à ocorrência de doenças."));
        list.add(new Flower(R.drawable.gerbera, "Gérbera", "Maio", "Com cerca de duas dezenas de tonalidades, que vão do branco ao vermelho, a gérbera é uma flor ideal para embelezar ambientes com cores intensas e vibrantes. Muito popular,  é uma planta herbácea, perene e fácil de ser cultivada. Não exige muitos cuidados e tem boa adaptação em regiões de clima seco. Como é rústica, tolera solos mais secos, porém, em períodos de pouca chuva, deve contar com regas regulares, de uma a duas vezes por semana.\\nO cultivo da flor deve ser realizado em local arejado e onde há incidência de sol. Propagada por sementes, tem em geral na segunda floração a aparência mais vistosa. Com até 40 centímetros de altura, ela conta com variedades para corte e para plantio em vasos (que são exemplares de desenvolvimento mais compacto)."));
        list.add(new Animal(R.drawable.gavial, "Gavial", "Essa espécie de crocodilo faz parte da família Gavialidae e pode ser encontrado nos rios da Índia.\n" +
                "\n" +
                "O crocodilo Gavial é um dos maiores de sua espécie, podendo ultrapassar os 6 metros de comprimento e sua mandíbula é composta por 110 dentes. Seus hábitos alimentares são de peixes e animais menores e essa espécie passa grande parte da sua vida na água, saindo somente para terra quando precisa depositar seus ovos."));
        list.add(new Animal(R.drawable.barbirusa, "Babirusas", "Essa espécie de mamíferos foi encontrada pela primeira vez na região da Indonésia.\n" +
                "\n" +
                "Sua aparência um tanto “pré-histórica” foi usada como inspiração para máscaras grotescas de demônios, isso porque os machos dessa espécie possuem presas no focinho. As babirusas são também reconhecidas como porcos selvagens. Apesar dessa espécie não ser conhecida pela maioria das pessoas, a caça acabou colaborando com a diminuição da sua população. Atualmente, as babirusas se encontram em perigo de extinção."));
        list.add(new Flower(R.drawable.crisantemo, "Crisântemo", "Junho", "Flor dourada é o significado da palavra crisântemo em grego, embora suas pétalas possam mostrar uma ampla gama de cores. Além dessa diversidade, o crisântemo apresenta ainda cultivares com botões de formatos diferentes, tornando-se uma excelente opção para decorar ambientes.\nO crisântemo se desenvolve bem em períodos de dias curtos, florescendo naturalmente no inverno."));
        list.add(new Animal(R.drawable.isopode, "Isópodo gigante", "Denominado também de Bathynomus giganteus, os isópodos gigantes são crustáceos encontrados nas águas frias dos oceanos Atlântico, Pacífico e Índico.\n" +
                "\n" +
                "Descoberta em 1879, essa espécie é uma das mais antigas dos nossos oceanos! Sua estrutura corporal pode atingir de 8 a 15 cm enquanto outros, denominados de “supergigantes”, chegam a ter de 17 a 50 cm! Felizmente, os isópodos gigantes não são o principal alvo da pesca pois se encontram nos ambientes mais inóspitos do oceano. Os hábitos alimentares desta espécie são baseados em restos dos animais mortos no oceano."));
        list.add(new Flower(R.drawable.lisianto, "Lisianto", "Junho", "Originariamente, o lisianto é de cor roxa ou branca, com pétalas simples, como é muito comum no Japão, onde foi iniciado, já na década de 1930, o melhoramento genético da planta, ampliando-se assim a oferta de cores e formas das pétalas das flores.\n" +
                "\n" +
                "Suscetível a pragas e doenças, o plantio de lisianto demanda atenção do produtor. Para ter mais segurança no manejo, o ideal é consultar um profissional da área agrícola. Um engenheiro agrônomo habilitado pode elaborar um programa de pulverizações de acordo com as condições climáticas da região e com a fase do cultivo."));
        list.add(new Flower(R.drawable.minimargarida, "Minimargarida", "Julho", "Entre as mais de 20 mil espécies de margaridas, o equivalente a mais de 10% das flores existentes no mundo, as miniaturas se destacam pela graciosidade do porte reduzido dos botões.\n" +
                "\n" +
                "Pequenas e delicadas, as margaridinhas, como também são chamadas na versão mini da flor, têm miolo amarelo, cercado por pétalas de diversos tons. Semelhante aos exemplares convencionais, se adaptam a qualquer clima e se proliferam facilmente, mesmo em solos mais secos. No entanto, terrenos com bastante matéria orgânica, boa capacidade de drenagem e estrutura dão suporte para garantir uma planta anual."));
        list.add(new Flower(R.drawable.azaleia, "Azálea", "Julho", "Branco, rosa, vermelho e tons mesclados são as principais cores da flor, que tem plantio espalhado pelo mundo. Apesar de resistentes, as azaleias estão sujeitas a ataques de algumas pragas, que podem ser combatidas com inseticidas biodegradáveis e à base de água.\n" +
                "\n" +
                "Em geral, tornam-se vulneráveis ao avanço de pulgões, cochonilhas, tripes e moscas-minadoras por causa das condições inadequadas do processo de plantio. Entre elas estão regas irregulares, condições deficientes de luz e/ou de ventilação, baixa umidade relativa ou muitas plantas instaladas em uma área muito restrita."));
        list.add(new Flower(R.drawable.begonia, "Begónia", "Maio", "Com formatos e tonalidades variadas, a begônia é uma das opções de planta bem aceitas no mercado, além de ser fácil de lidar para quem quer cultivá-la. Destinada para ornamentação, a begônia pode atingir até 30 centímetros de altura. Com folhagens verdes ou avermelhadas e bordas recortadas, a planta floresce bem na maior parte do ano. Embora seja uma espécie perene, pode ser cultivada como uma planta anual.\n" +
                "\n" +
                "Há muitas variedades de begônia para plantio, que podem ser divididas entre as mais adequadas para vaso e outras para jardins, as quais são mais indicadas para quem está iniciando a atividade de cultivo. O processo de propagação em canteiro é mais simples e as flores também têm a possibilidade de ser transferidas para vasos grandes e jardineiras."));
        list.add(new Animal(R.drawable.bico, "Bico de Tamanco", "Popularmente conhecido como Bico de tamanco, a espécie Balaeniceps rex é denominada assim por seu bico achatado em forma de sapato.\n" +
                "\n" +
                "Suas características lembram animais como cegonhas, pelicanos e garças. Durante a idade adulta pode atingir até 1 metro de altura, sendo reconhecido por seu andar lento e pela capacidade de manter-se imóvel por longos períodos de tempo. Seu habitat natural está distribuído no centro tropical da África, sul do Sudão, Congo, Ruanda, Uganda e Tanzânia. Atualmente, essa bela espécie encontra-se em perigo de extinção."));
        list.add(new Flower(R.drawable.jacinto, "Jacinto", "Agosto", "De cores intensas, a flor, cuja altura varia de 20 a 50 centímetros, tem tamanho adequado e beleza para fazer parte de qualquer ambiente de residências, estabelecimentos comerciais e locais públicos.\n" +
                "\n" +
                "Perfumada, a flor do jacinto aromatiza naturalmente o lugar onde se encontra, proporcionando uma sensação de proximidade com a natureza. Como seu exuberante e colorido florescimento ocorre na primavera, particularmente em regiões de clima frio, onde as condições naturais permitem que o bulbo passe por uma fase de dormência, que acontece durante todo o inverno, a planta é uma ótima opção para celebrar a alegre estação das flores."));
        list.add(new Flower(R.drawable.hortensia, "Hortênsia", "Maio", "Pouco comum entre as plantas, a cor azul é a característica marcante da hortênsia (Hydrangea macrophylla), flor de cultivo fácil, rápido e simples para produção comercial. Rústica e de boa adaptação a diferentes tipos de solos, a hortênsia ainda se destaca quanto à exuberância dos cachos que possui, os quais são muito utilizados para adornar diferentes ambientes.\n" +
                "\n" +
                "Disponibilidade de água e temperatura adequada são as maiores exigências para o bom desenvolvimento da hortênsia. Como é originalmente de clima ameno, a planta, oriunda da China e do Japão, não se dá muito bem em regiões quentes e secas. No entanto, por meio de técnicas de melhoramento genético, há algumas variedades da flor cultivadas em diversos países de clima tropical, temperado e subtropical."));

        list.add(new Animal(R.drawable.raroxa, "Rã roxa", "Descoberta somente em 2007 na região ocidental da Índia, a rã roxa vive enterrada a mais de 3 m da superfície.\n" +
                "\n" +
                "Seus lugares favoritos são os solos úmidos próximos às montanhas. A alimentação dessa espécie é baseada em cupins, pequenos vermes e formigas. O seu tamanho pode variar entre 6 a 9 cm enquanto a sua tonalidade característica é marrom e roxo. Suas patas são curtas e fortes já que precisam cavar a terra. Incrível, não é? Apesar de ser pequena a rã roxa é um anfíbio extraordinário."));
        list.add(new Animal(R.drawable.engolidor, "Engolidor Negro", "Denominado também de grande engolidor, a espécie do gênero Chiasmodon é uma das que habitam as águas profundas dos oceanos Atlântico, Pacífico e Índico.\n" +
                "\n" +
                "O seu corpo alongado pode chegar a medir 25 cm e sua estrutura não possui espinhas. Quanto a aparência do engolidor negro, sua boca contém vários dentes e seu estômago pode se expandir dependendo do animal de que se alimentou."));
        list.add(new Animal(R.drawable.komodo, "Dragão de Komodo", "O maior de todos os lagartos, o dragão de Komodo é um réptil poderoso que pesa até 300 quilos e pode atingir um comprimento de mais de 2 metros.\n" +
                "\n" +
                "Entre as vantagens predatórias podemos listar: velocidade, força e tenacidade para derrubar presas duas vezes maiores. Eles também têm uma mordida tóxica; qualquer vítima que sobrevive a um ataque do dragão de Komodo é suscetível a sucumbir aos seus ferimentos pouco depois. Eles principalmente caçam suas presas por emboscada, mas eles também são corredores rápidos e bons nadadores. Além do mais, a sua incrível habilidade predatória é acompanhada por uma igualmente impressionante capacidade de consumir carne, até a metade do seu peso próprio em uma única refeição."));
        list.add(new Animal(R.drawable.urso, "Urso Pardo", "O urso pardo é provavelmente o animal mais temido na América do Norte. Este poderoso animal pode medir 2,13 metros de altura e pesar mais de 800 quilos.\n" +
                "\n" +
                "Suas patas fortes e enormes pode matar um homem em uma única pancada, e as suas poderosas mandíbulas permitem que se alimentem de uma grande variedade de alimentos, incluindo mamíferos de grande porte. Ursos também são fortes nadadores e corredores rápidos. Se deparar com esse animal desses pode ser uma experiência angustiante, mas a melhor resposta é ficar parado e resistir ao impulso de correr. Estes animais foram cronometrados a mais de 40 quilômetros por hora."));

        return list;
    }
}


